### PR TITLE
update to truedread/netflix-1080p v1.12

### PR DESCRIPTION
**Pull request by ItsNickBarry**
This includes the files from the `1.11` release of `truedread/netflix-1080p`.  There appear to have been more changes since #13.

I have not updated the version number.

### CODE REVIEW

**Comment by informatorius** [comment]
Fixes issue https://github.com/vladikoff/netflix-1080p-firefox/issues/12

**Comment by Agouri** [comment]
Can this be merged to master, please? The add-on is currently broken

**Comment by ItsNickBarry** [comment]
Discussions in [truedread/netflix-1080p](https://github.com/truedread/netflix-1080p) indicate that this fix is no longer working for all content on Netflix, though I can confirm that it does work for some.

If you'd like to try it:
1. disable the plugin
1. `git clone https://github/itsnickbarry/netlix-1080p-firefox`
1. navigate to `about:debugging` in Firefox
1. choose "Load Temporary Add-on..." and select `src/manifest.json` from the cloned repository

**Comment by ItsNickBarry** [comment]
[v1.12](https://github.com/truedread/netflix-1080p/releases/tag/v1.12) causes titles which cannot be played in 1080p to fall back to 720p, rather than fail to play at all.

**Comment by ItsNickBarry** [comment]
Apparently some titles still fail to play in `v1.12`, but presumably it's better than `v1.11`.

**Comment by vladikoff** [comment]
Thanks!

**Pull request merged**
